#!/bin/bash

# Zsh Configuration Module
# Installs and configures Zsh with Oh My Zsh and Powerlevel10k

set -eo pipefail

# Load configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/lib/config_parser.sh"

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

MANAGED_ZSHRC_MARKER="# linux-env-setup managed zsh config"

tailscale_alias_block() {
    if [[ "$INSTALL_TAILSCALE" != "true" ]]; then
        return 0
    fi

    cat <<'EOF'
# Tailscale aliases
alias ts="sudo tailscale"
alias tsstatus="sudo tailscale status"
alias tsip="sudo tailscale ip"
alias tsping="sudo tailscale ping"
alias tsup="sudo tailscale up"
alias tsdown="sudo tailscale down"

EOF
}

is_managed_zshrc() {
    local file="$1"

    [[ -f "$file" ]] && grep -Fq "$MANAGED_ZSHRC_MARKER" "$file"
}

should_write_managed_zshrc() {
    local file="$1"

    [[ ! -f "$file" ]] || is_managed_zshrc "$file"
}

render_managed_zshrc() {
    local tailscale_block=""

    tailscale_block="$(tailscale_alias_block)"

    cat <<EOF
$MANAGED_ZSHRC_MARKER
# Generated by linux-env-setup. Re-running the installer may update this file.

# Enable Powerlevel10k instant prompt
if [[ -r "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh" ]]; then
  source "\${XDG_CACHE_HOME:-\$HOME/.cache}/p10k-instant-prompt-\${(%):-%n}.zsh"
fi

# Oh My Zsh configuration
export ZSH="\$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
    docker
    docker-compose
    npm
    node
    python
    pip
    sudo
    history
)

source \$ZSH/oh-my-zsh.sh

# Environment variables
export EDITOR='vim'
export LANG=en_US.UTF-8

# NVM configuration
export NVM_DIR="\$HOME/.nvm"
[ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"
[ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"

# pyenv configuration
export PYENV_ROOT="\$HOME/.pyenv"
export PATH="\$PYENV_ROOT/bin:\$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "\$(pyenv init -)"
fi

# Aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gco='git checkout'
alias gb='git branch'

# Docker aliases
alias dps='docker ps'
alias dimg='docker images'
alias dcp='docker compose'
alias dcup='docker compose up'
alias dcdown='docker compose down'
alias dcbuild='docker compose build'

# Workspace aliases
alias workspace='cd ~/workspace 2>/dev/null || echo "Workspace not found"'
alias projects='cd ~/workspace/projects 2>/dev/null || echo "Projects directory not found"'

${tailscale_block}# Work functions
newproject() {
    if [[ -z "\$1" ]]; then
        echo "Usage: newproject <project_name>"
        return 1
    fi
    
    local project_dir="\$HOME/workspace/projects/\$1"
    mkdir -p "\$project_dir"
    cd "\$project_dir"
    echo "Project directory created: \$project_dir"
}

# Powerlevel10k configuration
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
EOF
}

write_managed_zshrc() {
    local user="$1"
    local user_home="/home/$user"
    local zshrc_file="$user_home/.zshrc"
    local temp_file

    temp_file="$(mktemp)"
    render_managed_zshrc > "$temp_file"
    sudo mv "$temp_file" "$zshrc_file"
    sudo chown "$user:$user" "$zshrc_file"
    sudo chmod 644 "$zshrc_file"

    print_success "Managed .zshrc written for $user"
}

# Configure Zsh for a specific user
configure_zsh_for_user() {
    local user="$1"
    local user_home="/home/$user"
    local zshrc_file="$user_home/.zshrc"
    local zshrc_preexisting=false

    echo -e "${BLUE}🐚 Configuring Zsh for $user...${NC}"

    # Check if user exists
    if ! id "$user" &>/dev/null; then
        print_warning "User $user does not exist, skipping"
        return 0
    fi

    if [[ -f "$zshrc_file" ]]; then
        zshrc_preexisting=true
    fi

    if [[ "$(getent passwd "$user" | cut -d: -f7)" != "/bin/zsh" ]]; then
        sudo usermod -s /bin/zsh "$user"
        print_success "Default shell updated to /bin/zsh for $user"
    fi

    # Install Oh My Zsh for the user
    if [[ ! -d "$user_home/.oh-my-zsh" ]]; then
        sudo -u "$user" bash -lc 'tmp_file="$(mktemp)"; curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -o "$tmp_file"; RUNZSH=no CHSH=no KEEP_ZSHRC=yes sh "$tmp_file" --unattended; rm -f "$tmp_file"'
        print_success "Oh My Zsh installed for $user"
    else
        print_warning "Oh My Zsh already installed for $user"
    fi

    # Install Powerlevel10k theme
    if [[ ! -d "$user_home/.oh-my-zsh/custom/themes/powerlevel10k" ]]; then
        sudo -u "$user" bash -c "cd '$user_home' && git clone --depth=1 https://github.com/romkatv/powerlevel10k.git '$user_home/.oh-my-zsh/custom/themes/powerlevel10k'"
        print_success "Powerlevel10k installed for $user"
    else
        print_warning "Powerlevel10k already installed for $user"
    fi

    # Install zsh plugins
    local plugins_dir="$user_home/.oh-my-zsh/custom/plugins"

    if [[ ! -d "$plugins_dir/zsh-autosuggestions" ]]; then
        sudo -u "$user" bash -c "cd '$user_home' && git clone --depth=1 https://github.com/zsh-users/zsh-autosuggestions '$plugins_dir/zsh-autosuggestions'"
        print_success "zsh-autosuggestions installed for $user"
    fi

    if [[ ! -d "$plugins_dir/zsh-syntax-highlighting" ]]; then
        sudo -u "$user" bash -c "cd '$user_home' && git clone --depth=1 https://github.com/zsh-users/zsh-syntax-highlighting.git '$plugins_dir/zsh-syntax-highlighting'"
        print_success "zsh-syntax-highlighting installed for $user"
    fi

    if [[ "$zshrc_preexisting" == true ]] && ! should_write_managed_zshrc "$zshrc_file"; then
        print_warning "Existing unmanaged .zshrc detected for $user; leaving it unchanged"
        return 0
    fi

    write_managed_zshrc "$user"

    print_success "Zsh configuration completed for $user"
}

main() {
    # Parse configuration
    parse_config "$(resolve_config_file_path)"
    
    echo -e "${BLUE}🐚 Configuring Zsh for users...${NC}"
    
    local zsh_users_count=0
    
    for user in "${USERS[@]}"; do
        if user_has_zsh "$user"; then
            configure_zsh_for_user "$user"
            ((zsh_users_count++))
        fi
    done
    
    if [[ $zsh_users_count -eq 0 ]]; then
        echo -e "${BLUE}⏭️  No users configured for Zsh${NC}"
    else
        print_success "Zsh configuration completed for $zsh_users_count users"
    fi
}

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
