#!/bin/bash

# Department Setup Module
# Creates department structure and user accounts

set -eo pipefail

# Load configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/lib/config_parser.sh"

# Color definitions
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

declare -a CREATED_USERS=()
WORKSPACE_DIRECTORY_CREATED=false
TEAM_GROUP_CREATED=false

manifest_path() {
    printf '/opt/%s/.linux-env-setup-manifest\n' "$DEPARTMENT_NAME"
}

append_created_user() {
    local user="$1"
    local existing_user

    for existing_user in "${CREATED_USERS[@]}"; do
        if [[ "$existing_user" == "$user" ]]; then
            return 0
        fi
    done

    CREATED_USERS+=("$user")
}

load_manifest() {
    local file
    file="$(manifest_path)"

    if [[ -f "$file" ]]; then
        # shellcheck disable=SC1090
        source "$file"
    fi
}

write_manifest() {
    local manifest_file
    local temp_file
    local user

    manifest_file="$(manifest_path)"
    temp_file="$(mktemp)"

    {
        echo "# Generated by linux-env-setup on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        printf 'WORKSPACE_DIRECTORY_CREATED=%s\n' "$WORKSPACE_DIRECTORY_CREATED"
        printf 'TEAM_GROUP_CREATED=%s\n' "$TEAM_GROUP_CREATED"
        printf 'CREATED_USERS=('
        for user in "${CREATED_USERS[@]}"; do
            printf '%q ' "$user"
        done
        echo ')'
    } > "$temp_file"

    sudo mv "$temp_file" "$manifest_file"
    sudo chown root:root "$manifest_file"
    sudo chmod 600 "$manifest_file"

    print_success "Install manifest saved to $manifest_file"
}

# Generate secure password
generate_password() {
    openssl rand -base64 16
}

# Create workspace directory structure
create_department_structure() {
    echo -e "${BLUE}🏢 Creating workspace structure...${NC}"

    if [[ ! -d "/opt/$DEPARTMENT_NAME" ]]; then
        WORKSPACE_DIRECTORY_CREATED=true
    fi

    sudo mkdir -p "/opt/$DEPARTMENT_NAME"/{projects,shared,docs,scripts,archives}

    if ! getent group "$DEPARTMENT_NAME-team" >/dev/null 2>&1; then
        sudo groupadd "$DEPARTMENT_NAME-team"
        TEAM_GROUP_CREATED=true
    fi

    print_success "Workspace structure prepared at /opt/$DEPARTMENT_NAME"
}

# Create user accounts
create_users() {
    echo -e "${BLUE}👥 Creating user accounts...${NC}"
    
    local password_file="/opt/$DEPARTMENT_NAME/user-passwords.txt"
    
    # Create password file with secure permissions
    sudo touch "$password_file"
    sudo chown root:root "$password_file"
    sudo chmod 600 "$password_file"
    
    for user in "${USERS[@]}"; do
        if ! id "$user" &>/dev/null; then
            # Generate secure password
            user_pass=$(generate_password)
            
            # Determine shell
            if user_has_zsh "$user"; then
                shell="/bin/zsh"
            else
                shell="/bin/bash"
            fi
            
            # Create user
            sudo useradd -m -s "$shell" -G "$DEPARTMENT_NAME-team" "$user"
            echo "$user:$user_pass" | sudo chpasswd
            if command -v chage >/dev/null 2>&1; then
                sudo chage -d 0 "$user"
            fi
            
            # Save password to secure location
            echo "$user:$user_pass" | sudo tee -a "$password_file" > /dev/null
            append_created_user "$user"
            
            print_success "Created user: $user"
        else
            print_warning "User $user already exists"
        fi
        
        # Create workspace link
        sudo ln -sf "/opt/$DEPARTMENT_NAME" "/home/$user/workspace" 2>/dev/null || true
    done
}

# Set directory permissions
set_permissions() {
    echo -e "${BLUE}🔐 Setting directory permissions...${NC}"
    
    # Set department directory permissions
    sudo chown -R "root:$DEPARTMENT_NAME-team" "/opt/$DEPARTMENT_NAME"
    sudo chmod -R 775 "/opt/$DEPARTMENT_NAME"
    
    # Keep the password file root-only even when the workspace is group-writable.
    local password_file="/opt/$DEPARTMENT_NAME/user-passwords.txt"
    if [[ -f "$password_file" ]]; then
        sudo chown root:root "$password_file"
        sudo chmod 600 "$password_file"
    fi
    
    print_success "Directory permissions set"
}

# Create department info file
create_department_info() {
    echo -e "${BLUE}📄 Creating workspace information file...${NC}"
    
    local info_file="/opt/$DEPARTMENT_NAME/workspace-info.txt"
    local temp_info_file

    temp_info_file="$(mktemp)"
    
    cat > "$temp_info_file" << EOF
${DEPARTMENT_NAME^} Workspace Setup - $(date)
================================================

Workspace Directory: /opt/$DEPARTMENT_NAME
Team Group: $DEPARTMENT_NAME-team

Users Created:
EOF

    for user in "${USERS[@]}"; do
        echo "- $user" >> "$temp_info_file"
        if user_has_zsh "$user"; then
            echo "  - Shell: Zsh (with Oh My Zsh)" >> "$temp_info_file"
        else
            echo "  - Shell: Bash" >> "$temp_info_file"
        fi
        if user_has_docker "$user"; then
            echo "  - Docker: Yes" >> "$temp_info_file"
        else
            echo "  - Docker: No" >> "$temp_info_file"
        fi
    done
    
    cat >> "$temp_info_file" << EOF

Important Notes:
1. New users are required to change passwords on first login
2. Workspace directory: /opt/$DEPARTMENT_NAME
3. User workspace shortcut: ~/workspace
4. Initial credentials are stored in a root-only file: /opt/$DEPARTMENT_NAME/user-passwords.txt
EOF

    if [[ "$INSTALL_DOCKER" == "true" ]]; then
        echo "5. Users need to log out and back in for Docker permissions to take effect" >> "$temp_info_file"
    fi
    
    sudo mv "$temp_info_file" "$info_file"
    sudo chown "root:$DEPARTMENT_NAME-team" "$info_file"
    sudo chmod 644 "$info_file"
    
    print_success "Workspace info saved to: $info_file"
}

main() {
    # Parse configuration
    parse_config "$(resolve_config_file_path)"
    load_manifest
    
    create_department_structure
    create_users
    set_permissions
    create_department_info
    write_manifest
    
    print_success "Workspace setup completed"
}

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
